language: node_js
node_js:
- '13'
sudo: required
dist: bionic
addons:
  chrome: stable

cache: npm
install:
  - npm ci
script: skip
jobs:
  include:
  - stage: test
    name: Run Tests
    script:
    - npm run test
  - stage: deploy
    name: Deploy Production Version
    if: branch = main
    script:
    - npm run data
    - npm run build
    - cp dist/ccf-asct-reporter/index.html dist/ccf-asct-reporter/404.html
    - touch dist/ccf-asct-reporter/.nojekyll
    deploy:
      provider: pages
      target-branch: gh-pages
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: false
      local-dir: dist/ccf-asct-reporter
      on:
        branch: main
  - stage: deploy
    name: Deploy Staging Version
    if: branch = develop
    script:
    - npm run build:staging
    - cp dist/v2/index.html dist/v2/404.html
    - touch dist/v2/.nojekyll
    deploy:
      provider: pages
      target-branch: staging
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: false
      local-dir: dist/v2
      on:
        branch: develop
  - stage: test
    name: Test building production version on PRs
    if: type = pull_request
    script:
    - npm run build
  - stage: test
    name: Run linter
    script:
    - npm run lint
notifications:
  slack:
    secure: kmHjR6duu+E+c+JEBLjECE5mSboVOrz599dOubVU7eqwVNUGvbe3YDGIKAc0S6akqsW0q9bVUWM2Zi+J4ROHrlMi1A+VQRJAW+2DG+6wu8fmdZiA0u/fK2w9IMRPFDDk80mMZN7TzSPMu5nRv6UGbVqpNeqRWotd2XtyLOu3+KRYKggUjKKz5D3oiYYGaHZWj6foDG7u42q33RQ55LlWff0GmAUuYVSfOUlxAYevOTuV9QF8NfFRnlQAfIYucM9177dd9cfWUdRgWPL7VGDUrANF2NtrfTUcWMM/zl6Vk7KMTxcCr1Oy0osxPE4DlpD8Mdz+i54tqKtcopJirBUnogZx+6MoMqMpTu7mU9pmB1H5rhAqlddYUMxiiyUvAvsScm3G5tY7azvqB0i6qalveTXuZWTa3CZUKHHTkDaDd0tnCvnLqWUaxZ2TeS//67q4EvreTfIdD4hD4phXjqfS+x0Ha8w7MpjwNln651svxsnpv+Ak6ET8N/NVRY61LhzAocMHitqMZMycTgyf8l5rciUtWE2cIuDiH86SBF+KeDYnoCCBwN8qXUTktVie37PeBX2drO84wNc8tmzjpIguXyCQUCBN/t0BodC4BIH+/oasfsYtKpXj6LQaV4/brf+t+hZX2FYssS44UZAKn3CQ92Mp7YurngUMHBqaMC6wPu4=
