name: Netlify Preview Deploy

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

concurrency:
  group: preview-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare Deploy
        uses: ./.github/actions/prepare-deploy
        with:
          main-branch-name: develop
          app-configuration: preview
          build-compodoc: false
          build-storybook: false

      - name: Publish
        id: deploy
        uses: South-Paw/action-netlify-cli@v2
        with:
          args: deploy --dir=deploy/apps/ccf
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Create Deploy Comment
        uses: ./.github/actions/deploy-comment
        with:
          deploy-url: ${{steps.deploy.outputs.NETLIFY_PREVIEW_URL}}
