name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.15.1
      uses: actions/setup-node@v1
      with:
        node-version: 8.15.1
    - name: Build and Deploy
      uses: hrishikeshpaul/ccf-asctb-reporter@main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: main
        BRANCH: gh-pages
        FOLDER: dist/v2
        BUILD_SCRIPT: npm install && npm run build:v2
