name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm install -g @angular/cli > /dev/null
    - run: npm run build:v2
    - name: Publish generated content to GitHub Pages
      uses: hrishikeshpaul/ccf-asctb-reporter@v1.0.1
      with:
          dir: dist/v2
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
