name: Staging Build

on:
  workflow_run:
    workflows: ['CI']
    branches: ['develop']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: Prepare Deploy
        uses: ./.github/actions/prepare-deploy
        with:
          main-branch-name: develop
          app-configuration: staging
          nx-command: run-many
          build-compodoc: false
          build-storybook: false

      - name: Setup Netlify files
        run: |
          echo '/* /index.html 200' > deploy/apps/ccf/_redirects
      - name: Setup additional pages
        run: |
          cp -r static/* deploy/apps/ccf/
          cp deploy/apps/ccf/index.html deploy/apps/ccf/404.html
          touch deploy/apps/ccf/.nojekyll

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: deploy/apps/ccf
          publish_branch: staging
          commit_message: 'Staging deploy -- ${{ github.event.head_commit.message }}'
